### ISSUE TITLE
Ferramenta utilizada pra gerar as listas de bloqueio

### ISSUE THREAD

**Issue by fabioeidi20** [zangadoprojets/pi-hole-block-list#10]
Ola, poderia compartilhar que ferramenta vc usa pra gerar essas listas de bloqueio? Foi alguma coisa que vc desenvolveu, ou utiliza algum script/tool ja pronto?

Quero customizar as minhas proprias listas e estou procurando as ferramentas apropriadas.

Aproveitando, outra duvida: vejo na lista do tiktok que tem alguns IPs listados (exemplo abaixo). Isso tem alguma aplicabilidade ou significado em listas de bloqueio baseadas em DNS? Pelo que entendo, quando vc coloca direto um IP no browser, ele nao realiza uma pesquisa DNS e conecta direto...? Am I missing something?

	161.117.70.136
	161.117.70.145
	161.117.70.68
	161.117.70.89
	161.117.71.34
	161.117.71.35
	161.117.71.73
	161.117.71.74
	34.196.79.125
	47.252.102.182
	47.252.102.193
	47.252.102.198
	47.252.102.48
	47.252.102.50
	47.252.50.101
	47.252.50.1571

Obrigado

**Comment by zangadoprojets** [comment]
Amigo, as listas são de vários projetos da internet, inclusive aqui mesmo no github tem vários. O que fiz foi juntar as listas, fazer a organização, retirar duplicidades e fazer um projeto mais completo.  Para organizar as listas uso o Visual Studio mesmo, com expressão regular para retirar duplicidades e espaços em branco, tipo:
Linhas em branco:  ^(\s)*$\n
Duplicatas: ^(.*)(\n\1)+$

Valeu!

**Comment by dalinong** [comment]
Tem como adicionar elas via scrpit ? ou tem que ser lista a lista ? e caso pois se eu quiser voltar a liberar o tiktok eu vou ter que excluir aquelas 45 mil entradas ?

**Comment by zangadoprojets** [comment]
Só desabilitar no pi-hole!
