### ISSUE TITLE
Precisei colocar em whitelist o domínio www.googleadservices.com

### ISSUE THREAD

**Issue by barbosa-emb** [zangadoprojets/pi-hole-block-list#13]
Não sei se está correto o bloqueio, mas precisei colocar em whitelist essa url pra poder clicar nos anúncios de compra que o google exibe.

Exemplo: coloquei SSD 2Tb no buscador e gostei de um anuncio da Shopee. Só consegui clicar após incluir a url em whitelist.

Porém, compreendo que seja anúncio.

**Comment by zangadoprojets** [comment]
O foco da lista é bloquear os anúncios mesmo. Mas obrigado por contribuir com o projeto!
