### ISSUE TITLE
thepiratebay.org na lista de mining pages

### ISSUE THREAD

**Issue by Squiercg** [zangadoprojets/pi-hole-block-list#15]
A página do piratebay continua minerando no computador dos outros? Ele estã na lista de mining pages.

Como eu as vezes baixo torrent de la, eu deixei no whitelist, mas fiquei pensando porque a página estava na lista.

Eu achei esse artigo:
https://torrentfreak.com/the-pirate-bay-website-runs-a-cryptocurrency-miner-170916/

Que comentava que o piratebay tinha colocado um script de mineração na página deles, mas não na pagina inicial, mas em resultados, listas, etc.

Eu tenho procurado esse codigo no pirate bay, ou algo semelhante e não tenho encontrado. Nem algo semelhante, será que ainda continua la, será que eles mantém essa prática?

**Comment by koobzaar** [comment]
Sim, continua. Não é nem minimamente recomendado. 

Para mais informações, por favor, busque no Reddit r/Piracy e acesse a Megathread deles. Lá você vai encontrar sites alternativos, além também dos motivos pelos quais o TPB foi bloqueado.
