### ISSUE TITLE
Porn paginas, algumas do Brr estão passando

### ISSUE THREAD

**Issue by robcs85** [zangadoprojets/pi-hole-block-list#17]
Pesquisando algumas páginas por "porno brasileiro" no google, estão abrindo. Outras estão funcionando 100%

Páginas como estas abaixo, estão abrindo normal:
https://pornobrasil.com/ 
https://br.xhamster.com/categories/brazilian
https://www.pornobengala.com/videos/porno-brasileiro/
https://xvidiosx.com/videos/porno-brasileiro/
https://www.pornolandia.xxx/videos/porno-brasileiro/
https://pornobrasil.blog.br/
https://www.pornodoido.com/videos-porno/porno-brasileiro/
https://xvideosbr.to/porno-brasileiro/
https://xxxvideos.blog/video-porno-brasileiro/
https://www.pornobrasileiro.tv/

**Comment by zangadoprojets** [comment]
Obrigado pela Contribuição. Sites incluídos
