### ISSUE TITLE
revenuecat.com não pode ser bloqueado

### ISSUE THREAD

**Issue by dpedrinha** [zangadoprojets/pi-hole-block-list#19]
RevenueCat é um provedor de serviços pra compras dentro de apps Android e iOS que cria uma API unificada pras duas lojas de apps facilitando o desenvolvimento de apps com IAPs.

Com esse domínio bloqueado muitos aplicativos perderiam a funcionalidade de compras e assinaturas dentro do app.
Além disso os dados coletados por eles são minimamente invasivos e contabilizam apenas compras, assinaturas e cancelamentos com identificadores anônimos próprios.

Sou dev e utilizo a plataforma deles nos meus apps. Facilita muito o trabalho pra pequenos desenvolvedores.

Farei um pull request removendo-o. É contigo. Mas recomendo fortemenete que você aceite. 

Abraço

**Comment by zangadoprojets** [comment]
Aceito. Obrigado pela contribuição!
