### ISSUE TITLE
Domínios de miniatura de fotos do YouTube e compartilhamento de links da Amazon estão bloqueados - problemas com conexão de SmartTV Samsung

### ISSUE THREAD

**Issue by koobzaar** [zangadoprojets/pi-hole-block-list#22]
Todos estão relacionados com o Adsandtrackers.

amzn.to - URL shortener da Amazon no compartilhamento de links
ytimg.com - servidor responsável pelas fotos dos canais do YouTube e suas miniaturas
estão ambos bloqueados.

Isto logicamente implica em dois erros:
- Ao clicar em links compartilhados diretamente da Amazon, não é possível acessar o anúncio. amzn.to é o equivalente a youtu.be.
- Ao navegar na home do YouTube, canais aparecem sem fotos de perfil. 

Alguns links da Smart TV da Samsung de importância para integridade da conexão estão bloqueados. São inúmeros, mas, [essa adlist](https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt) da uma dica de quais não devem ser e seus motivos.
Ao utilizar sua lista, aplicativos e até mesmo a própria detecção de rede da SmartTV param de funcionar.

Lista de domínions a serem permitidos:
mhc-ajax-eu.myhomescreen.tv
mhc-ajax-eu-s2.myhomescreen.tv
mhc-ajax-us.myhomescreen.tv
mhc-eu.myhomescreen.tv
mhc-us.myhomescreen.tv
mhc-xpana-eu.myhomescreen.tv
mhc-xpana-eu-s2.myhomescreen.tv
mhc-xpana-us.myhomescreen.tv
vcs.vdspf.com
applicast.ga.sony.net
portal.store.sonyentertainmentnetwork.com
reg.biv.sony.tv
service.biv.sony.tv
ssm1.internet.sony.tv
ssm2.internet.sony.tv
ssm3.internet.sony.tv
update.biv.sony.tv
platform.cid.samba.tv
ngfts.lge.com
us.lgtvsdp.com
deviceportal.nettvservices.com
epg.corio.com
www.ecdinterface.philips.com
acr0.samsungcloudsolution.com
configprd.samsungcloudsolution.net
dev-multiscreen.samsung.com
gpm.samsungqbe.com
multiscreen.samsung.com
samsungrm.net
auth.samsungosp.com
cdn.samsungcloudsolution.com
infolink.pavv.co.kr
lcprd1.samsungcloudsolution.net
otnprd10.samsungcloudsolution.net
otnprd11.samsungcloudsolution.net
otnprd8.samsungcloudsolution.net
otnprd9.samsungcloudsolution.net
samsungosp.com
samsungotn.net
time.samsungcloudsolution.com
www.samsungotn.net
osb-ussvc.samsungqbe.com
otn.samsungcloudcdn.com
ns11.whois.co.kr
api.vizio.com
images.vizio.com
hbbtv.prosieben.de
hbbtv.redbutton.de
hbbtv.zdf.de
api.nfl.com
apicache.vudu.com
cdns-content.dzcdn.net
drscdn.500px.org
geo.opera.com
itv.ard.de
tv.deezer.com
secure.netflix.com
api-global.netflix.com
appboot.netflix.com
nrdp.nccp.netflix.com
nrdp.prod.ftl.netflix.com
api-tv.spotify.com
time-a.timefreq.bldrdoc.gov
api.accuweather.com
tuner-api.hdhomerun.com
location-api.hdhomerun.com
avpro.global.yamaha.com
file2fxm.azureedge.net

Motivos:

URL: mhc-ajax-eu.myhomescreen.tv
Motivo pelo qual deve ser permitido: teste de conexão com a internet
URL: mhc-ajax-eu-s2.myhomescreen.tv
Motivo pelo qual deve ser permitido: teste de conexão com a internet
URL: mhc-ajax-us.myhomescreen.tv
Motivo pelo qual deve ser permitido: teste de conexão com a internet
URL: mhc-eu.myhomescreen.tv
Motivo pelo qual deve ser permitido: necessário para conectividade com a internet
URL: mhc-us.myhomescreen.tv
Motivo pelo qual deve ser permitido: necessário para conectividade com a internet
URL: mhc-xpana-eu.myhomescreen.tv
Motivo pelo qual deve ser permitido: necessário para iniciar aplicativos
URL: mhc-xpana-eu-s2.myhomescreen.tv
Motivo pelo qual deve ser permitido: necessário para iniciar aplicativos
URL: mhc-xpana-us.myhomescreen.tv
Motivo pelo qual deve ser permitido: necessário para iniciar aplicativos
URL: vcs.vdspf.com
Motivo pelo qual deve ser permitido: se bloqueado, notifica sobre novo firmware, mas não consegue baixar/instalar
URL: applicast.ga.sony.net
Motivo pelo qual deve ser permitido: necessário para aplicativos
URL: portal.store.sonyentertainmentnetwork.com
Motivo pelo qual deve ser permitido: necessário para aplicativos, se bloqueado, apresenta erro "sem conexão com a internet"
URL: update.biv.sony.tv
Motivo pelo qual deve ser permitido: necessário para atualizações
URL: us.lgtvsdp.com
Motivo pelo qual deve ser permitido: #117
URL: deviceportal.nettvservices.com
Motivo pelo qual deve ser permitido: necessário para aplicativos
URL: epg.corio.com
Motivo pelo qual deve ser permitido: necessário para aplicativos
URL: auth.samsungosp.com
Motivo pelo qual deve ser permitido: se bloqueado, as contas samsung não serão autenticadas
URL: cdn.samsungcloudsolution.com
Motivo pelo qual deve ser permitido: Verificação de atualização do sistema na Samsung UE40F5500
URL: infolink.pavv.co.kr
Motivo pelo qual deve ser permitido: Necessário para appstore e login na Samsung UE40F5500
URL: otnprd10.samsungcloudsolution.net
Motivo pelo qual deve ser permitido: necessário para atualização de software
URL: otnprd11.samsungcloudsolution.net
Motivo pelo qual deve ser permitido: necessário para atualização de software
URL: otnprd8.samsungcloudsolution.net
Motivo pelo qual deve ser permitido: necessário para atualização de software
URL: otnprd9.samsungcloudsolution.net
Motivo pelo qual deve ser permitido: necessário para atualização de software
URL: samsungotn.net
Motivo pelo qual deve ser permitido: verificação de atualização do sistema na Samsung UE65RU7455
URL: time.samsungcloudsolution.com
Motivo pelo qual deve ser permitido: se bloqueado, serviços como Plex, YouTube e Amazon Video não funcionam mais em algumas TVs Samsung
URL: www.samsungotn.net
Motivo pelo qual deve ser permitido: necessário para atualização de software
URL: osb-ussvc.samsungqbe.com
Motivo pelo qual deve ser permitido: necessário para TV Plus
URL: api.vizio.com
Motivo pelo qual deve ser permitido: Necessário para os recursos da smart tv Vizio
URL: images.vizio.com
Motivo pelo qual deve ser permitido: Necessário para os recursos da smart tv Vizio
URL: api.nfl.com
Motivo pelo qual deve ser permitido: necessário para o aplicativo NFL Fantasy Football
URL: apicache.vudu.com
Motivo pelo qual deve ser permitido: necessário para o aplicativo Vudu, veja issue22
URL: geo.opera.com
Motivo pelo qual deve ser permitido: bloqueia a atualização do Opera
URL: secure.netflix.com
Motivo pelo qual deve ser permitido: quebra a Netflix
URL: api-global.netflix.com
Motivo pelo qual deve ser permitido: quebra a Netflix
URL: appboot.netflix.com
Motivo pelo qual deve ser permitido: quebra a Netflix
URL: nrdp.nccp.netflix.com
Motivo pelo qual deve ser permitido: A reprodução da Netflix falha no Humax DTR-T2100 (YouView) STB
URL: api-tv.spotify.com
Motivo pelo qual deve ser permitido: necessário para o aplicativo de TV e PS4 spotify
URL: tuner-api.hdhomerun.com
Motivo pelo qual deve ser permitido: necessário para atualização de firmware
URL: location-api.hdhomerun.com
Motivo pelo qual deve ser permitido: necessário para atualização de firmware
URL: avpro.global.yamaha.com
Motivo pelo qual deve ser permitido: Bloqueia atualizações do sistema no RX-V685

Além disso, a API dos roteadores/modem da Xiaomi estão bloqueados:
api.miwifi.com
No geral, não se sabe se deve ou não ser bloqueado. No entanto, nenhuma lista o bloqueia. 
Ao bloquear, os roteadores tentarão a cada segundo contactar o servidor sem parar - resultando em um spam abusurdo nas estatísticas do Pi-Hole
![MiWifi responsável por quase 90% dos bloqueios de rede](https://github.com/zangadoprojets/pi-hole-blocklist/assets/48564736/f33b459a-8589-4b4c-a139-67870bad59d8)

**Comment by zangadoprojets** [comment]
Obrigado pela contribuição. Os domínios foram retirados!
