### ISSUE TITLE
portlists.txt contains Australian IT News site

### ISSUE THREAD

**Issue by subi75** [zangadoprojets/pi-hole-block-list#3]
The Pornlists.txt file incorrectly lists itnews.com.au as a porn site.
This domain is owned and used by an IT News company as their site, and therefore should not be listed in the blocklists (particularly any porn list).
If you do not agree, please provide exact URL details to assist in justifying why the domain should be blocked.

**Comment by zangadoprojets** [comment]
Removed url! Thanks for reporting!
