### ISSUE TITLE
Bloqueio do serviço do Windows Update na lista Telemetry

### ISSUE THREAD

**Issue by dmirandaa** [zangadoprojets/pi-hole-block-list#5]
A lista ```telemetry.txt``` está bloqueando o serviço de atualização do Windows.

Existe algum motivo de segurança ou privacidade?

**Comment by zangadoprojets** [comment]
Uso aqui com Windows 11, não tive problemas com atualizações ainda, olha que está tendo muita atualização para Windows 11, você usa qual versão?

**Comment by dmirandaa** [comment]
O bloqueio do Windows Update ocorreu em uma máquina que havia acabado de instalar o Windows 11 (22H2). Desativei o bloqueio do pi-hole e na sequência iniciou a atualização.

Mas isso só ocorreu nesse momento, depois de instalar as primeiras atualizações e no uso diário parece não bloquear.

Acho que carece de mais testes pra saber se o domínio ```download.windowsupdate.com``` deve ser removido ou não da lista.

**Comment by zangadoprojets** [comment]
Ok, me mantenha atualizado, até o momento não tive problemas.

**Comment by dmirandaa** [comment]
Consegui reproduzir ativando a lista ```telemetry.txt``` e rodando o Update Gravity.

![Screenshot_20230313-104556-001](https://user-images.githubusercontent.com/2193615/224723080-f93632d8-00bb-4983-9570-4b1c8f074f28.png)

O domínio que está bloqueando especificamente o Windows Update no Windows 11 é ```slscr.update.microsoft.com```

![Screenshot_20230313-105023-001](https://user-images.githubusercontent.com/2193615/224723237-626ae6e0-5dfc-4605-aeed-76515663515f.png)

Coloquei na lista de permitidos e voltou a funcionar o Windows Update.

![Screenshot_20230313-105331-001](https://user-images.githubusercontent.com/2193615/224723707-5bbf2831-72df-4d7c-8cf9-11d70b5b1340.png)

**Comment by zangadoprojets** [comment]
Obrigado pelo retorno. Já retirei da lista!
