### ISSUE TITLE
Bloqueio do youtube.com na lista Adsandtrackers

### ISSUE THREAD

**Issue by dmirandaa** [zangadoprojets/pi-hole-block-list#6]
O naked domain do ```youtube.com``` está na lista de bloqueio ```Adsandtrackers.txt```

Os links de compartilhamento do Youtube Shorts são enviados com o naked domain ```youtube.com```, diferente dos links de vídeos padrão compartilhados com o domínio ```youtu.be```

**Comment by zangadoprojets** [comment]
Não entendi seu questionamento, está bloqueando Youtube Shorts? Qual sugestão de alteração?

**Comment by dmirandaa** [comment]
Quando tento acessar o link [https://youtube.com/shorts/0afnOL0BhZY?feature=share](https://youtube.com/shorts/0afnOL0BhZY?feature=share) a requisição é bloqueada.

Consegui reproduzir aqui só depois de ativar a lista ```Adsandtrackers.txt``` e rodar o UpdateGravity.

O link é gerado na tela de compartilhamento do Youtube.

![Screenshot_20230313-103900-001](https://user-images.githubusercontent.com/2193615/224719849-49e16b8c-a43b-47e3-8e08-ff38a7feb1ab.png)

**Comment by zangadoprojets** [comment]
Ok, preciso estudar esse bloqueio de ads do youtube, nunca funcionou efetivamente. Vou analisar isso.

**Comment by fabioeidi20** [comment]
So complementando, a lista Adsandtrackers.txt tem muitos "false positives". Dominios legitimos como play.google.com, facebook.com, youtube.com e outros estao nela...

Se a intencao eh ter um jeito de bloquear a categoria toda de social media, talvez melhor criar uma nova lista dedicada so pra isso, e dai poderia botar o TikTok no bolo...

Valeu!

**Comment by zangadoprojets** [comment]
Fiz algumas alterações na lista. Obrigado
