### ISSUE TITLE
Bloquear sites falso 123milhas 

### ISSUE THREAD

**Issue by claudineyqr** [zangadoprojets/pi-hole-block-list#8]
Bloquear sites. Estes são falsos. Aplicam fraude (golpes) em vendas passagens aéreas e pacotes de viagens. 

123-vendasvoos25.lovestoblog.com
c-123milhas.shop

**Comment by zangadoprojets** [comment]
Sites incluídos. Se tiver mais pode enviar. Obrigado por contribuir.
